package com.stan.lightphotobackup.database
enum class BackupStatus { DISCOVERED, PENDING, UPLOADING_BYTES, AWAITING_MEDIA_CREATION, UPLOADED, RETRYABLE_FAILURE, PERMANENT_FAILURE, MISSING_LOCAL_FILE }
