import {afterEach,describe,expect,it} from "vitest";
import request from "supertest";
import crypto from "node:crypto";
import {createApp,normalizePairingCode} from "./app.js";
import {loadConfig} from "./config.js";
import {Store} from "./store.js";
import type {GoogleProvider} from "./google.js";
import {hashSecret,redact,TokenCipher} from "./security.js";

class FakeGoogle implements GoogleProvider {
  state?:string; challenge?:string;
  authorizationUrl(state:string,challenge:string){this.state=state;this.challenge=challenge;return `https://accounts.google.com/o/oauth2/v2/auth?state=${encodeURIComponent(state)}&scope=${encodeURIComponent("https://www.googleapis.com/auth/photoslibrary.appendonly")}&access_type=offline`;}
  async exchange(){return "refresh";}
  async access(){return {accessToken:"access",expiresAt:new Date(Date.now()+1000).toISOString(),scope:"https://www.googleapis.com/auth/photoslibrary.appendonly"};}
  async revoke(){}
}
const stores:Store[]=[];
const setup=(ttl=600)=>{const c=loadConfig({NODE_ENV:"test",PUBLIC_BASE_URL:"http://localhost",PAIRING_TTL_SECONDS:String(ttl),GOOGLE_CLIENT_SECRET:"must-never-appear-in-html",TOKEN_ENCRYPTION_KEY_BASE64:crypto.randomBytes(32).toString("base64")});const s=new Store(":memory:");const google=new FakeGoogle();stores.push(s);return {c,s,google,app:createApp(c,s,google)};};
const startPath=(html:string)=>{const match=/href="(\/oauth\/google\/start\/[A-Za-z0-9_-]+)"/.exec(html);expect(match).toBeTruthy();return match![1]!;};
afterEach(()=>{while(stores.length)stores.pop()!.close();});

describe("browser pairing",()=>{
 it("uses a same-origin form and preserves CSP",async()=>{const x=setup();const response=await request(x.app).get("/connect");expect(response.status).toBe(200);expect(response.text).toContain('method="post" action="/connect"');expect(response.text).not.toContain("must-never-appear-in-html");expect(response.headers["content-security-policy"]).toContain("form-action 'self'");});
 it("normalizes supported pairing code variants",()=>{for(const value of ["ABCD-EFGH","ABCDEFGH","abcd-efgh","abcd efgh","  abcd_efgh  "])expect(normalizePairingCode(value)).toBe("ABCD-EFGH");expect(normalizePairingCode("BAD")).toBeNull();});
 it("returns a local confirmation page and associates state",async()=>{const x=setup();const made=await request(x.app).post("/api/v1/pairing/sessions");const response=await request(x.app).post("/connect").type("form").send({pairingCode:made.body.pairingCode.toLowerCase().replace("-"," ")});expect(response.status).toBe(200);expect(response.headers.location).toBeUndefined();expect(startPath(response.text)).toMatch(/^\/oauth\/google\/start\//);expect(response.text).not.toContain("accounts.google.com");expect(response.text).not.toContain("must-never-appear-in-html");expect(response.headers["content-security-policy"]).toContain("form-action 'self'");const session=x.s.session(made.body.pairingId)!;expect(session.state_hash).toBeTruthy();expect(session.verifier).toBeTruthy();expect(x.s.oauthStartCount()).toBe(1);});
 it("start link redirects to Google once and preserves original state",async()=>{const x=setup();const made=await request(x.app).post("/api/v1/pairing/sessions");const confirmation=await request(x.app).post("/connect").type("form").send({pairingCode:made.body.pairingCode});const path=startPath(confirmation.text);const first=await request(x.app).get(path);expect(first.status).toBe(302);expect(first.headers.location).toMatch(/^https:\/\/accounts\.google\.com\//);const state=x.google.state!;expect(x.s.session(made.body.pairingId)?.state_hash).toBe(hashSecret(state.split(".")[1]!));const replay=await request(x.app).get(path);expect(replay.status).toBe(410);expect(replay.headers.location).toBeUndefined();});
 it("rejects expired and unknown OAuth-start tokens",async()=>{const x=setup();const made=await request(x.app).post("/api/v1/pairing/sessions");const expired="e".repeat(32);x.s.createOAuthStart(hashSecret(expired),made.body.pairingId,"state",Date.now()-1);expect((await request(x.app).get(`/oauth/google/start/${expired}`)).status).toBe(410);expect((await request(x.app).get(`/oauth/google/start/${"u".repeat(32)}`)).status).toBe(410);});
 it("invalid and expired codes do not create start tokens",async()=>{const x=setup();for(const code of ["BAD","ZZZZ-ZZZZ"]){const response=await request(x.app).post("/connect").type("form").send({pairingCode:code});expect(response.status).toBe(400);expect(response.headers.location).toBeUndefined();expect(response.text).toContain("form");}expect(x.s.oauthStartCount()).toBe(0);const expired=setup(-1);const made=await request(expired.app).post("/api/v1/pairing/sessions");expect((await request(expired.app).post("/connect").type("form").send({pairingCode:made.body.pairingCode})).status).toBe(410);expect(expired.s.oauthStartCount()).toBe(0);});
 it("OAuth callback completes the same pairing session",async()=>{const x=setup();const made=await request(x.app).post("/api/v1/pairing/sessions");const confirmation=await request(x.app).post("/connect").type("form").send({pairingCode:made.body.pairingCode.replace("-","")});expect(confirmation.status).toBe(200);expect((await request(x.app).get(startPath(confirmation.text))).status).toBe(302);const response=await request(x.app).get("/oauth/google/callback").query({code:"valid-code",state:x.google.state});expect(response.status).toBe(200);expect(response.text).toContain("PHOTO BACKUP CONNECTED");expect(x.s.session(made.body.pairingId)?.status).toBe("connected");const poll=await request(x.app).get(`/api/v1/pairing/sessions/${made.body.pairingId}`);expect(poll.body.status).toBe("connected");expect(poll.body.deviceCredential).toBeTruthy();});
});

describe("server security",()=>{
 it("health reveals no configuration or secrets",async()=>{const x=setup();const response=await request(x.app).get("/health");expect(response.status).toBe(200);expect(response.body).toEqual({status:"ok"});expect(response.text).not.toContain("must-never-appear-in-html");expect(response.text).not.toContain("database");});
 it("creates and expires pairing sessions",async()=>{const x=setup(-1);const made=await request(x.app).post("/api/v1/pairing/sessions");expect(made.status).toBe(201);expect((await request(x.app).get(`/api/v1/pairing/sessions/${made.body.pairingId}`)).body.status).toBe("expired");});
 it("delivers a connected credential once",async()=>{const x=setup(),made=await request(x.app).post("/api/v1/pairing/sessions"),credential="x".repeat(43),cipher=new TokenCipher(x.c.key);x.s.connect(made.body.pairingId,"device",cipher.encrypt(credential),hashSecret(credential),cipher.encrypt("refresh"),Date.now()+10000);expect((await request(x.app).get(`/api/v1/pairing/sessions/${made.body.pairingId}`)).body.deviceCredential).toBe(credential);expect((await request(x.app).get(`/api/v1/pairing/sessions/${made.body.pairingId}`)).body.deviceCredential).toBeUndefined();});
 it("hashes credentials, encrypts tokens, and redacts logs",()=>{expect(hashSecret("a")).toHaveLength(64);const c=new TokenCipher(crypto.randomBytes(32)),encrypted=c.encrypt("secret");expect(encrypted).not.toContain("secret");expect(c.decrypt(encrypted)).toBe("secret");expect(redact({authorization:"Bearer x",nested:{refreshToken:"y"}})).toEqual({authorization:"[REDACTED]",nested:{refreshToken:"[REDACTED]"}});});
 it("protects tokens and disconnect",async()=>{const x=setup();expect((await request(x.app).post("/api/v1/tokens/google")).status).toBe(401);const cred="c".repeat(43);x.s.connect("missing","dev",cred,hashSecret(cred),new TokenCipher(x.c.key).encrypt("refresh"),Date.now()+10000);expect((await request(x.app).post("/api/v1/tokens/google").set("Authorization",`Bearer ${cred}`)).body.accessToken).toBe("access");expect((await request(x.app).delete("/api/v1/devices/current").set("Authorization",`Bearer ${cred}`)).status).toBe(204);});
 it("rejects invalid OAuth state",async()=>{const x=setup();expect((await request(x.app).get("/oauth/google/callback?code=abcdef&state=invalidstate")).status).toBe(400);});
});
