import express from "express";
import helmet from "helmet";
import {rateLimit} from "express-rate-limit";
import {z} from "zod";
import type {Config} from "./config.js";
import type {GoogleProvider} from "./google.js";
import {pkceChallenge} from "./google.js";
import {Store} from "./store.js";
import {hashSecret,pairingCode,randomToken,TokenCipher} from "./security.js";

const page=(body:string)=>`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Photo Backup</title><link rel="stylesheet" href="/styles.css"></head><body>${body}</body></html>`;
const connectPage=(message?:string)=>page(`<h1>PHOTO BACKUP</h1><p>Enter the code shown on your Light Phone.</p>${message?`<p role="alert">${message}</p>`:""}<form method="post" action="/connect"><input name="pairingCode" maxlength="16" autocomplete="one-time-code" required><button type="submit">CONNECT GOOGLE ACCOUNT</button></form>`);
const confirmationPage=(startToken:string)=>page(`<h1>CONNECT GOOGLE ACCOUNT</h1><p>Your pairing code was accepted.</p><p><a href="/oauth/google/start/${startToken}">CONTINUE TO GOOGLE</a></p>`);
const OAUTH_START_TTL_MS=5*60_000;
export function normalizePairingCode(value:unknown):string|null {
 if(typeof value!=="string")return null;
 const compact=value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");
 return /^[A-Z0-9]{8}$/.test(compact)?`${compact.slice(0,4)}-${compact.slice(4)}`:null;
}
export function createApp(config:Config,store:Store,google:GoogleProvider){
 const app=express(); if(config.trustProxy)app.set("trust proxy",config.trustProxy); app.disable("x-powered-by"); app.use(helmet({hsts:config.production?{maxAge:31536000,includeSubDomains:true,preload:false}:false,referrerPolicy:{policy:"no-referrer"},contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'none'"],styleSrc:["'self'"],imgSrc:["'none'"],connectSrc:["'self'"],fontSrc:["'self'"],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"],frameAncestors:["'none'"],upgradeInsecureRequests:config.production?[]:null}}})); app.use(express.json({limit:"16kb"})); app.use(express.urlencoded({extended:false,limit:"16kb"}));
 app.use("/api",rateLimit({windowMs:60_000,limit:60,standardHeaders:true,legacyHeaders:false}));
 if(config.production)app.use((req,res,next)=>req.secure?next():res.status(400).json({error:"HTTPS required"}));
 const cipher=new TokenCipher(config.key);
 const bearer=(req:express.Request)=>{const m=/^Bearer ([A-Za-z0-9_-]{40,})$/.exec(req.header("authorization")??"");return m?.[1]};
 app.get("/health",(_q,r)=>r.json({status:"ok"}));
 app.get("/styles.css",(_q,r)=>r.type("css").send("body{font:18px system-ui;max-width:32rem;margin:4rem auto;padding:1rem;background:#000;color:#fff}input,button{font:inherit;padding:.8rem;margin:.5rem 0;width:100%;box-sizing:border-box}button{background:#fff;color:#000;border:0}"));
 app.post("/api/v1/pairing/sessions",(_q,r)=>{const id=randomToken(24),code=pairingCode(),expires=Date.now()+config.pairingTtlSeconds*1000;store.createSession({id,code_hash:hashSecret(code),status:"pending",expires_at:expires,attempts:0,state_hash:null,verifier:null,device_id:null,credential_once:null});r.status(201).json({pairingId:id,pairingCode:code,verificationUrl:`${config.publicBaseUrl}/connect`,expiresAt:new Date(expires).toISOString(),pollIntervalSeconds:config.pollSeconds});});
 app.get("/api/v1/pairing/sessions/:id",(q,r)=>{const s=store.session(q.params.id);if(!s)return r.status(404).json({error:"Pairing session not found"});if(s.expires_at<=Date.now()&&s.status==="pending"){return r.json({status:"expired"});}if(s.status==="connected"){const encrypted=store.consumeCredential(s.id);return r.json(encrypted?{status:"connected",deviceCredential:cipher.decrypt(encrypted)}:{status:"connected"});}return r.json({status:s.status});});
 app.get("/connect",(_q,r)=>r.type("html").send(connectPage()));
 app.post("/connect",(q,r)=>{const code=normalizePairingCode(q.body?.pairingCode);if(!code)return r.status(400).type("html").send(connectPage("Enter a valid eight-character pairing code."));const s=store.byCode(hashSecret(code));if(!s||s.expires_at<=Date.now()||s.status!=="pending"||s.attempts>=5){if(s)store.incrementAttempts(s.id);return r.status(s?.expires_at && s.expires_at<=Date.now()?410:400).type("html").send(connectPage("That pairing code is invalid or has expired. Please try again."));}const state=randomToken(),verifier=randomToken(48),startToken=randomToken(24);try{google.authorizationUrl(`${s.id}.${state}`,pkceChallenge(verifier));}catch{return r.status(503).type("html").send(page("<h1>SERVER NOT CONFIGURED</h1><p>Google OAuth credentials are required.</p>"));}store.setOAuth(s.id,hashSecret(state),verifier);store.createOAuthStart(hashSecret(startToken),s.id,state,Date.now()+OAUTH_START_TTL_MS);return r.status(200).type("html").send(confirmationPage(startToken));});
 app.get("/oauth/google/start/:token",(q,r)=>{const token=z.string().regex(/^[A-Za-z0-9_-]{32,}$/).safeParse(q.params.token);if(!token.success)return r.status(400).type("html").send(page("<h1>INVALID CONNECTION LINK</h1><p>Return to the connection page and enter a new pairing code.</p>"));const start=store.consumeOAuthStart(hashSecret(token.data));if(!start||!start.session.state_hash||!start.session.verifier)return r.status(410).type("html").send(page("<h1>CONNECTION LINK EXPIRED</h1><p>Return to the connection page and enter a new pairing code.</p>"));try{return r.redirect(302,google.authorizationUrl(`${start.session.id}.${start.oauthState}`,pkceChallenge(start.session.verifier)));}catch{return r.status(503).type("html").send(page("<h1>SERVER NOT CONFIGURED</h1><p>Google OAuth credentials are required.</p>"));}});
 app.get("/oauth/google/callback",async(q,r)=>{const parsed=z.object({code:z.string().min(5),state:z.string().min(10)}).safeParse(q.query);if(!parsed.success)return r.status(400).type("html").send(page("<h1>CONNECTION FAILED</h1>"));const dot=parsed.data.state.indexOf(".");const id=parsed.data.state.slice(0,dot),secret=parsed.data.state.slice(dot+1),s=store.session(id);if(!s||!s.state_hash||hashSecret(secret)!==s.state_hash||!s.verifier||s.expires_at<=Date.now())return r.status(400).type("html").send(page("<h1>CONNECTION FAILED</h1>"));try{const refresh=await google.exchange(parsed.data.code,s.verifier),credential=randomToken(32),deviceId=randomToken(18);store.connect(s.id,deviceId,cipher.encrypt(credential),hashSecret(credential),cipher.encrypt(refresh),Date.now()+config.deviceTtlDays*86400000);return r.type("html").send(page("<h1>PHOTO BACKUP CONNECTED</h1><p>You can close this page and return to your Light Phone.</p>"));}catch{return r.status(502).type("html").send(page("<h1>CONNECTION FAILED</h1><p>Please try again.</p>"));}});
 app.post("/api/v1/tokens/google",async(q,r)=>{const credential=bearer(q);if(!credential)return r.status(401).json({error:"Unauthorized"});const d=store.device(hashSecret(credential));if(!d)return r.status(401).json({error:"Unauthorized"});try{return r.json(await google.access(cipher.decrypt(d.encrypted_refresh_token)));}catch{return r.status(503).json({error:"Token service unavailable"});}});
 app.delete("/api/v1/devices/current",async(q,r)=>{const credential=bearer(q);if(!credential)return r.status(401).json({error:"Unauthorized"});const d=store.device(hashSecret(credential));if(!d)return r.status(401).json({error:"Unauthorized"});const refresh=cipher.decrypt(d.encrypted_refresh_token);store.disconnect(d.id);await google.revoke(refresh);return r.status(204).send();});
 app.use((_q,r)=>r.status(404).json({error:"Not found"})); return app;
}
