package com.stan.lightphotobackup.pairing
import com.stan.lightphotobackup.BuildConfig
import android.util.Log
import kotlinx.serialization.json.Json
import okhttp3.*
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.time.Instant
class PairingHttpException(val status:Int):IOException("Auth server HTTP $status")
class AuthorizationExpiredException:IOException("Account connection expired")
class PairingApi(private val client:OkHttpClient,private val base:String=BuildConfig.AUTH_SERVER_BASE_URL){private val json=Json{ignoreUnknownKeys=true};val configured get()=base.startsWith("http://")||base.startsWith("https://");private fun url(path:String)=base.trimEnd('/')+path;suspend fun create()=execute(Request.Builder().url(url("/api/v1/pairing/sessions")).post(ByteArray(0).toRequestBody()).build()){json.decodeFromString<PairingSession>(it)};suspend fun poll(id:String)=execute(Request.Builder().url(url("/api/v1/pairing/sessions/$id")).build()){json.decodeFromString<PairingPoll>(it)};suspend fun token(credential:String):AccessTokenResponse{Log.i("PhotoBackupAuth","token request started");return execute(Request.Builder().url(url("/api/v1/tokens/google")).header("Authorization","Bearer $credential").post(ByteArray(0).toRequestBody()).build()){json.decodeFromString<AccessTokenResponse>(it)}};suspend fun disconnect(credential:String){execute(Request.Builder().url(url("/api/v1/devices/current")).header("Authorization","Bearer $credential").delete().build()){Unit}};private suspend fun<T>execute(request:Request,parse:(String)->T):T=kotlinx.coroutines.suspendCancellableCoroutine{cont->val call=client.newCall(request);cont.invokeOnCancellation{call.cancel()};call.enqueue(object:Callback{override fun onFailure(call:Call,e:IOException){cont.resumeWith(Result.failure(e))};override fun onResponse(call:Call,response:Response){response.use{if(request.url.encodedPath=="/api/v1/tokens/google")Log.i("PhotoBackupAuth","token response HTTP status=${it.code}");if(!it.isSuccessful){cont.resumeWith(Result.failure(PairingHttpException(it.code)));return};try{val value=parse(it.body?.string().orEmpty());if(request.url.encodedPath=="/api/v1/tokens/google")Log.i("PhotoBackupAuth","token request succeeded");cont.resumeWith(Result.success(value))}catch(e:Exception){cont.resumeWith(Result.failure(e))}}}})}}
class PairingRepository(private val api:PairingApi,private val store:SecureCredentialStore){private var cached:AccessTokenResponse?=null;fun connected()=store.get()!=null;suspend fun start()=api.create();suspend fun poll(id:String):PairingPoll=api.poll(id).also{if(it.status=="connected"&&it.deviceCredential!=null)store.save(it.deviceCredential)};suspend fun accessToken():String{cached?.takeIf{runCatching{Instant.parse(it.expiresAt).toEpochMilli()>System.currentTimeMillis()+120_000}.getOrDefault(false)}?.let{return it.accessToken};val c=store.get()?:throw AuthorizationExpiredException();return try{api.token(c).also{cached=it}.accessToken}catch(e:PairingHttpException){if(e.status==401)throw AuthorizationExpiredException();throw e}};suspend fun disconnect(){store.get()?.let{runCatching{api.disconnect(it)}};cached=null;store.clear()};val configured get()=api.configured}
